### ISSUE TITLE
[BUG]: Query does not refetch on the next mount

### ISSUE THREAD

**Issue by timsofteng** [suspensive/react#91] opened 2023-06-30 16:02 UTC
### **Package Scope**

Package name:
`suspensive/react`

### **Describe the bug**

broken query triggers boundary but it does not refetch it on the next mount.

### **Expected behavior**

Query should be refetched on the second mount of the component

### **To Reproduce**

https://github.com/timsofteng/query-boundary-bug

`suspensive` branch

steps:

yarn install && yarn dev
Open http://127.0.0.1:5173/one
Click to page two. See an error in query and in boundary.
Click to page one. Page one should be rendered ok.
Click to page two. Boundary is displayed but query does not refetch.

**Comment by manudeli** [comment] 2023-07-03 15:34
@timsofteng 
What you mean is that you think ErrorBoundary should try to reset if there is a caught error? However, if ErrorBoundary tries to reset on every mount, it will make ErrorBoundary can't show fallback. so I don't think it's a good idea to force reset every mount.

If you have a good idea, could you please fork suspensive, and create a branch, and suggest it as a pull request with modifying @suspensive/react's code directly on websites/visualization? This way will make you can more clearly show what you want.

**Comment by manudeli** [comment] 2023-07-03 16:39
And I want to suggest this ErrorBoundaryGroup way to meet your needs

I want to modify https://github.com/timsofteng/query-boundary-bug/blob/suspensive/src/PageTwo.tsx  like below code.
@suspensive/react's ErrorBoundaryGroup will easily trigger ErrorBoundary's reset in parent.

Could you resolve your problem in this way?

```tsx
import { useEffect, useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import { useNavigate } from 'react-router-dom'
import { useFetchTodo } from './api'
import { ErrorBoundary } from './ErrorBoundary'
import {
  useErrorBoundaryGroup,
  withErrorBoundaryGroup,
} from '@suspensive/react'

const PageTwo = withErrorBoundaryGroup(function PageTwo() {
  const group = useErrorBoundaryGroup()

  useEffect(() => {
    group.reset()
  })

  return (
    <ErrorBoundary>
      <Wrapped />
    </ErrorBoundary>
  )
})

export default PageTwo

function Wrapped() {
  const [count, setCount] = useState(0)

  const navigate = useNavigate()
  useFetchTodo()

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Page 2</h1>
      <button onClick={() => navigate('/one')}>to page one</button>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}


```

**Comment by timsofteng** [comment] 2023-07-03 22:21
@manudeli 
Thank you for your reply and for your solution.
To be honest I still have don't understand why it doesn't work just out of the box in my example.
Why do we need this strange useEffect and additional hook?
Expected behavior is just send another request on mount after this failed component was unmounted. 

Please notice that it works exactly as I expected if we change route "/one/two" just to route "/two".

**Comment by timsofteng** [comment] 2023-07-03 22:28
Your solution means we should manually reset existed boundary for the component which was unmounted previously. But I don't understand why is this boundary existed for it.

**Comment by timsofteng** [comment] 2023-07-04 14:03
The best solution which I've tried was this inside of the fallback component
```
  useEffect(() => {
    return () => {
      queryClient.removeQueries({
        predicate: (q) => q.state.status === "error",
      });
    };
  }, []);
```

**Comment by manudeli** [comment] 2023-07-04 14:57
@timsofteng 

> The best solution which I've tried was this inside of the fallback component
> 
> ```
>   useEffect(() => {
>     return () => {
>       queryClient.removeQueries({
>         predicate: (q) => q.state.status === "error",
>       });
>     };
>   }, []);
> ```

However, I think this will work against your intentions. Because you're intending to just try to show the children of this ErrorBoundary when the webpage returns to "/two", right? But this will show the fallback first and then the fallback will be shown first and inside the fallback it will call queryClient.removeQueries and then show ErrorBoundary.children.

I don't think this order is what you want. What do you think?

**Comment by timsofteng** [comment] 2023-07-04 15:42
@manudeli May you please describe it clearly? Please notice that hook will be triggered on unmount of fallback component in my example.

**Comment by timsofteng** [comment] 2023-07-04 16:01
@manudeli we definitely need some solution for this issue and both your solutions sounds good.
The only one thing I'm worried about is this issue exists only for routes `/one` `/one/two` and doesn't exist for routes `/one` `/two`. I have no idea why.

**Comment by manudeli** [comment] 2023-07-04 16:10
You mean no refetching when revisiting `/two` not `/one/two`? I could meet this issue in my local machine right now when `/one`, `/two` too same with `/one`, `/one/two`. Could you show me video or gif capturing your display? I couldn't reproduce it like you.

**Comment by timsofteng** [comment] 2023-07-04 16:36
@manudeli nevermind. I was wrong. It doesn't work in both cases

**Comment by manudeli** [comment] 2023-08-06 12:58
@timsofteng I'll close this issue first, but if there issue again, you can reopen this issue too. 👍

**Closed by manudeli** 2023-08-06 12:58 UTC
Labels: enhancement
